/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import covid.tracker.Vertice;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import covid.tracker.Grafo;

/**
 *
 * @author JPPM
 */
public class Ventana extends javax.swing.JFrame {

    int posicionX;
    int posicionY;
    private final float DISTANCIA_NODOS_X = 100;
    private final float DISTANCIA_NODOS_Y = 100;
    int contadorParaAgregarColumna;
    Grafo grafo;

    public Ventana() {
        initComponents();
        this.grafo = null;
        this.setVisible(true);
        this.setSize(1024, 600);
        this.jPanel1.setBackground(new Color(255, 205, 178));
        this.setResizable(false);

        posicionX = jPanel1.getWidth()/2;
        posicionY = jPanel1.getHeight()/2;
        contadorParaAgregarColumna = 0;
    }

    public void mostrarGrafo() {
        Graphics g = jPanel1.getGraphics();

        Vertice v = grafo.getPtr();

        int iterador = 0;

        while (v != null) {
            switch (iterador) {
                case 0:
                    posicionY = 200;
                    g.drawOval(posicionX, posicionY, 50, 50);
                    g.drawString(Integer.toString(v.getId()), posicionX + 25, posicionY + 30);
                    break;
                case 1:
                    posicionY -= DISTANCIA_NODOS_Y;
                    g.drawOval(posicionX, posicionY, 50, 50);
                    g.drawString(Integer.toString(v.getId()), posicionX + 25, posicionY + 30);
                    break;
                case 2:
                    posicionY += DISTANCIA_NODOS_Y * 2;
                    g.drawOval(posicionX, posicionY, 50, 50);
                    g.drawString(Integer.toString(v.getId()), posicionX + 25, posicionY + 30);
                    posicionX -= DISTANCIA_NODOS_X;
                    iterador = -1;
                    break;
                default:
                    break;
            }
            
            iterador++;

            v = (Vertice) v.getLink();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        $btn_mostrarGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        $btn_mostrarGrafo.setText("Mostrar Grafo");
        $btn_mostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                $btn_mostrarGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent($btn_mostrarGrafo)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent($btn_mostrarGrafo)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void $btn_mostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_$btn_mostrarGrafoActionPerformed
        this.grafo = new Grafo();
        grafo.generarGrafo();

        mostrarGrafo();
    }//GEN-LAST:event_$btn_mostrarGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton $btn_mostrarGrafo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
